[platformio]
# Указываем корень проекта, где лежат все папки
src_dir = ESP32-DIV/ESP32-DIV
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# ГОВОРИМ ИСКАТЬ В КОРНЕ ПАПКИ, А НЕ В SRC
build_src_filter = +<*> +<./>

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    nrf24/RF24@^1.4.7
    links2004/WebSockets@^2.4.1
    h2zero/NimBLE-Arduino@^1.4.1
    lsatan/Smartrc-CC1101-Driver-Lib@^3.0.1
    bblanchon/ArduinoJson@6.21.3
    xreef/PCF8574 library@^2.3.4
    zinggjm/GxEPD@^3.1.3
    kosme/arduinoFFT@^1.6.0

build_flags =
    -I ESP32-DIV/ESP32-DIV
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TOUCH_CS=21
    
