[platformio]
src_dir = ESP32-DIV/ESP32-DIV
include_dir = ESP32-DIV/ESP32-DIV

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
# Принудительно включаем поддержку .ino файлов
build_src_filter = +<*> +<../ESP32-DIV/ESP32-DIV/*.ino>

lib_deps =
    bodmer/TFT_eSPI
    nrf24/RF24
    links2004/WebSockets
    bblanchon/ArduinoJson
    https://github.com/pfeerick/pcf8574.git
    https://github.com/ZinggJM/GxEPD

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TOUCH_CS=21
    
