[platformio]
# Указываем путь к папке, где лежит .ino файл
src_dir = ESP32-DIV
include_dir = ESP32-DIV

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
# Помогаем найти код, если он в подпапке
build_src_filter = +<*> +<ESP32-DIV/*.ino>

lib_deps =
    bodmer/TFT_eSPI
    nrf24/RF24
    links2004/WebSockets
    bblanchon/ArduinoJson
    h2zero/NimBLE-Arduino
    xreef/PCF8574 library
    zinggjm/GxEPD
    kosme/arduinoFFT
    lsatan/Smartrc-CC1101-Driver-Lib

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TOUCH_CS=21
    
